# maybe dhall?
profiles:
  default: 
    roots:
      60: 60
      61: 61
      62: 62
      63: 63
      64: 64
      65: 65
      66: 66
      67: 67
      68: 68
      69: 69
      70: 70
      71: 71
    chord_types:
      72: MAJ
      73: MIN
      74: DIM
      74: AUG
